config/routes.rb
Zhuata::Application.routes.draw do

  devise_for :users do
    get "sign_in", :to => "devise/sessions#new", :as => :sign_in
    get "sign_up", :to => "registrations#new", :as => :sign_up
    get "sign_out", :to => "devise/sessions#destroy", :as => :sign_out
    get "users/edit_pwd", :to => "registrations#edit_pwd", :as => :edit_pwd
    get "users/edit_avatar", :to => "registrations#edit_avatar", :as => :edit_avatar
    put "users/update_pwd", :to => "registrations#update_pwd", :as => :update_pwd
    put "users/update_avatar", :to => "registrations#update_avatar", :as => :update_avatar
  end

  match 'audio_books/parse' => 'audio_books#parse' #, :as => :parse_audio_books
  resources :audio_books, :fictions, :pictures, :blogs do
    collection do
      get 'search'
    end
    resources :comments, only: [:index]
  end

  resources :comments

  match 'blogs/tag/:tags' => 'blogs#tag', :as => :tag_blogs
  match 'fictions/tag/:tags' => 'fictions#tag', :as => :tag_fictions
  match 'audio_books/tag/:tags' => 'audio_books#tag', :as => :tag_audio_books
  match ":user_id" => "blogs#index", :as => :user
  match ":user_id/blogs" => "blogs#index", :as => :user_blogs
  match ":user_id/audio_books" => "audio_books#index", :as => :user_audio_books
  match ":user_id/fictions" => "fictions#index", :as => :user_fictions
  match ":user_id/pictures" => "pictures#index", :as => :user_pictures

  match "fictions/:id/chapters" => "fictions#chapters", :as => :chapters_fictions

  match ":controller/search" => "blogs#search"

  root :to => 'welcome#index'

end

app/models/audio_book.rb
require 'models/content_field'
require 'models/spider_field'
require 'spider/core'

class AudioBook

  include ::ContentField
  include ::SpiderField

  key :talker, String

  many :chapters

end

app/controllers/audio_books_controller.rb
# encoding=utf-8
class AudioBooksController < ContentController

  def search
    seo_msg("有声读物 评书 小说搜索", "抓取 有声读物 评书 小说", 
            "关注 聆听自己喜欢的有声读物 评书 小说")
    super
  end

  def index
    seo_msg("有声读物 评书 小说", "抓取 有声读物 评书 小说", 
            "关注 聆听自己喜欢的有声读物 评书 小说")
    super
  end

  def parse
    url = params[:url]
    result = {state: 0, message: "arguments is not blank"}
    unless url.blank?
      result[:state] = 1
      result[:message] = Spider.read(Spider::AUDIO_BOOK_HASH, url)
    end
    render :json => result
  end
end

app/helpers/audio_books_helper.rb
module AudioBooksHelper
end

app/views/audio_books/_audio_book.html.slim
- user = audio_book.user || User.new
.item
  .content
    =link_to image_tag(user.avatar.url(:middle)), user_path(user.id)
    .header
      /=link_to user.name, user_path(user.id)
      span=audio_book.talker
      |&nbsp;&bull;&nbsp;
      =link_to raw(audio_book.title), audio_book_path(audio_book)
    p.body
      = raw cut_remove_html(audio_book.text, 200)
    ul.nav.pills.small
      - for tag in audio_book.tags
        li=link_to tag, tag_audio_books_path(tag)
    .footer
      =link_to user.name, user_path(user.id)
      span= time_ago_in_words audio_book.created_at
      span
        = t_submit("read")
        = " #{audio_book.read_count}"
      span
        = t_submit("comment")
        = " #{audio_book.comments_count}"
      - if current_user == user
        .pull-right
          = link_to t("helpers.submit.edit", model: ""), edit_audio_book_path(audio_book)
          a data-method="delete" href="#{audio_book_path(audio_book)}" rel="nofollow"
            = t("helpers.submit.delete", model: "")

app/views/audio_books/edit.html.slim
= alert(@audio_book)
.module.border
  .header
    h5= t_form_title(@audio_book, "edit")
  .body
    = form_for(@audio_book, url: audio_book_path, html: {class: "form"}) do |f|
      .fr
        = f.label :url, class: "label"
        .fd
          = f.text_field :url, style: "width: 80%;"
      .fr
        = f.label :title, class: "label"
        .fd
          = f.text_field :title, style: "width: 80%;"
      .fr
        = f.label :tags, class: "label"
        .fd
          = f.text_field :new_tags,
            value: @audio_book.new_tags || @audio_book.tags.join(',')
      .fr
        = f.label :talker, class: "label"
        .fd
          = f.text_field :talker
      .fr
        = f.label :text, class: "label"
        .fd
          = f.text_area :text, style: "width: 98%; height: 200px;"
      .form-actions
        = f.submit t_submit("update"), class: "btn blue"

- content_for :sidebar do
  = render partial: "partials/new"
  .module.border
    = render partial: "users/show_base", locals: {user: current_user}

app/views/audio_books/index.html.slim
=alert
.items.border
  .item.header
    h5= t("models.audio_book")
  = render @audio_books
  .item.footer= page @audio_books

- content_for :sidebar do
  = render partial: "partials/new"
  = render partial: "partials/hot_tags"
  = render partial: "users/sidebar"

app/views/audio_books/new.html.slim
= alert(@audio_book)
.module.border
  .header
    h5= t_form_title(@audio_book, "create")
  .body
    = form_for(@audio_book, url: audio_books_path, html: {class: "form"}) do |f|
      =f.hidden_field :talker
      =f.hidden_field :title
      =f.hidden_field :text
      .fr
        = f.label :url, class: "label"
        .fd
          = f.text_field :url, style: "width: 80%;"
          span.help.block
            = t("attributes.audio_book.support")
      .form-actions
        = f.submit t_submit("save"), class: "btn blue"

- content_for :sidebar do
  = render partial: "partials/new"
  .module.border
    = render partial: "users/show_base", locals: {user: current_user}

app/views/audio_books/show.html.slim
- user = @audio_book.user || User.new
.items.border
  .item
    .content.big
      =link_to image_tag(user.avatar.url(:thumb)), user_path(user.id)
      .header
        span= @audio_book.talker
        |&nbsp;&bull;&nbsp;
        =link_to @audio_book.title, @audio_book.url
      ul.nav.pills.small
        - for tag in @audio_book.tags
          li=link_to tag, tag_audio_books_path(tag)
      .footer
        =link_to user.name, user_path(user.id)
        span= time_ago_in_words @audio_book.created_at
        /! =link_to "#js-content-comments" do
        span
          = t_submit("comment")
          = " #{@audio_book.comments_count}"
        span
          = t_submit("read")
          = " #{@audio_book.read_count}"
        - if current_user == user
          .pull-right
            = link_to t("helpers.submit.edit", model: ""), edit_audio_book_path(@audio_book)
            a data-method="delete" href="#{audio_book_path(@audio_book)}" rel="nofollow"
              = t("helpers.submit.delete", model: "")
  .item
    p= raw @audio_book.text
  - if @audio_book.chapters.length > 0
    .item#js-audio-book-chapters
      ul.nav.pills.small
        - @audio_book.chapters.each do |chapter|
          li
            = link_to chapter.title, chapter.url, target: "_blank"
  / .item#js-chapter-content style="display:none"
  /   = render partial: "chapter"
  .item.active
    =render :partial => "comments/new"
  #js_paginate_result.items
  .item.footer= ajax_page(audio_book_comments_path(@audio_book.id))

- content_for :sidebar do
  = render partial: "partials/new"
  .module.border
    .inner
      audio#js-audio-control controls="controls" autoplay="autoplay"
        | Your browser does not support the audio tag.
  = render partial: "partials/related_contents"