config/routes.rb
Zhuata::Application.routes.draw do

  devise_for :users do
    get "sign_in", :to => "devise/sessions#new", :as => :sign_in
    get "sign_up", :to => "registrations#new", :as => :sign_up
    get "sign_out", :to => "devise/sessions#destroy", :as => :sign_out
    get "users/edit_pwd", :to => "registrations#edit_pwd", :as => :edit_pwd
    get "users/edit_avatar", :to => "registrations#edit_avatar", :as => :edit_avatar
    put "users/update_pwd", :to => "registrations#update_pwd", :as => :update_pwd
    put "users/update_avatar", :to => "registrations#update_avatar", :as => :update_avatar
  end

  match 'audio_books/parse' => 'audio_books#parse' #, :as => :parse_audio_books
  resources :audio_books, :fictions, :pictures, :blogs do
    collection do
      get 'search'
    end
    resources :comments, only: [:index]
  end

  resources :comments

  match 'blogs/tag/:tags' => 'blogs#tag', :as => :tag_blogs
  match 'fictions/tag/:tags' => 'fictions#tag', :as => :tag_fictions
  match 'audio_books/tag/:tags' => 'audio_books#tag', :as => :tag_audio_books
  match ":user_id" => "blogs#index", :as => :user
  match ":user_id/blogs" => "blogs#index", :as => :user_blogs
  match ":user_id/audio_books" => "audio_books#index", :as => :user_audio_books
  match ":user_id/fictions" => "fictions#index", :as => :user_fictions
  match ":user_id/pictures" => "pictures#index", :as => :user_pictures

  match "fictions/:id/chapters" => "fictions#chapters", :as => :chapters_fictions

  match ":controller/search" => "blogs#search"

  root :to => 'welcome#index'

end

app/models/comment.rb
class Comment
  include MongoMapper::Document

  key :text, String, required: true

  # many :replies

  timestamps!

  belongs_to :commentable, polymorphic: true, counter_cache: true
  belongs_to :user, counter_cache: true

  validates :commentable_id, presence: true

  ensure_index [[:commentable_id, 1], [:user_id, 1]]

end

app/controllers/comments_controller.rb
class CommentsController < BaseController

  def create
    @comment = Comment.new(params[:comment])
    @comment.user = current_user
    @comment.save
    render_ajax @comment
  end

  def index
    ["Blog", "AudioBook", "Fiction", "Picture"].each do |str|
      key = "#{str.tableize.singularize}_id"
      puts "::::key=#{params[key]}"
      if params[key]
        params[:commentable_id] = params[key]
        params[:commentable_type] = str
        params.delete(key)
        break
      end
    end

    @comments = Comment.page(params)
    respond_to do |format|
      format.html { render "index" }
      format.json { render_ajax_page @comments }
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
- user = comment.user || User.new
.item
  .content.small
    =link_to image_tag(user.avatar.url(:middle)), user_path(user.id)
    p.body
      = raw comment.text
    .footer
      =link_to user.name, user_path(user.id)
      span= time_ago_in_words comment.created_at
      /.pull-right
        a class="js-comment-reply-link" href="javascript:void(0);" data-comment-id="#{comment.id}" 
          =t_submit("reply")
    /div style="display:none; margin-top: 5px;"
    /.items

app/views/comments/_new.html.slim
- if user_signed_in?
  .js-form-simple style="margin-left: 60px;"
    = text_field_tag "", "来评论两句..", style: "width: 99%;"
  div style="display: none;"
    = form_for(@comment, url: comments_path, html: {class: "form"}) do |f|
      = f.hidden_field :commentable_id
      = f.hidden_field :commentable_type
      = f.text_area :text, class: "js-textarea"
      = f.submit "#{t("helpers.submit.title", model: t("helpers.submit.comment"))} Ctrl+Enter", 
        class: "btn blue disabled js-form-page"
- else
  p
    |需先登录，方可评论

app/views/comments/index.html.slim
.items.border
  = render @comments
  .item.footer= page @comments