config/routes.rb
Zhuata::Application.routes.draw do

  devise_for :users do
    get "sign_in", :to => "devise/sessions#new", :as => :sign_in
    get "sign_up", :to => "registrations#new", :as => :sign_up
    get "sign_out", :to => "devise/sessions#destroy", :as => :sign_out
    get "users/edit_pwd", :to => "registrations#edit_pwd", :as => :edit_pwd
    get "users/edit_avatar", :to => "registrations#edit_avatar", :as => :edit_avatar
    put "users/update_pwd", :to => "registrations#update_pwd", :as => :update_pwd
    put "users/update_avatar", :to => "registrations#update_avatar", :as => :update_avatar
  end

  match 'audio_books/parse' => 'audio_books#parse' #, :as => :parse_audio_books
  resources :audio_books, :fictions, :pictures, :blogs do
    collection do
      get 'search'
    end
    resources :comments, only: [:index]
  end

  resources :comments

  match 'blogs/tag/:tags' => 'blogs#tag', :as => :tag_blogs
  match 'fictions/tag/:tags' => 'fictions#tag', :as => :tag_fictions
  match 'audio_books/tag/:tags' => 'audio_books#tag', :as => :tag_audio_books
  match ":user_id" => "blogs#index", :as => :user
  match ":user_id/blogs" => "blogs#index", :as => :user_blogs
  match ":user_id/audio_books" => "audio_books#index", :as => :user_audio_books
  match ":user_id/fictions" => "fictions#index", :as => :user_fictions
  match ":user_id/pictures" => "pictures#index", :as => :user_pictures

  match "fictions/:id/chapters" => "fictions#chapters", :as => :chapters_fictions

  match ":controller/search" => "blogs#search"

  root :to => 'welcome#index'

end

app/views/partials/_footer.html.slim
.module.border
  .footer
    | Copyright © #{Time.new.year} myliang

app/views/partials/_guide.html.slim
.module.border
  .header
    h5 操作指南
  div style="padding: 10px 20px;"
    embed src='http://player.56.com/v_OTEyMjM5NjQ.swf' type='application/x-shockwave-flash' width='800' height='470' allowFullScreen='true' allowNetworking='all' allowScriptAccess='always'

app/views/partials/_hot_tags.html.slim
- if not @user and @hot_tags
  ul.nav.stacked
    li.active
      a 热门标签
    - @hot_tags.each do |tag|
      li
        = link_to "/#{controller_name}/tag/#{tag.name}" do
          strong= tag.name
          strong.gray-light
            |&nbsp;&nbsp;&times;&nbsp;
            = "#{tag.counter}"

app/views/partials/_new.html.slim
.module.border style="overflow:visible;"
  .inner
    .btn-group.menu-outer
      =link_to t("helpers.submit.new", model: t("models.#{controller_name.singularize}")), "/#{controller_name}/new", class: "btn green"
      a.btn.green.js-menu.last href="#"
        span class="caret down"
      = new_menus

app/views/partials/_related_contents.html.slim
- if @related_models
  ul.nav.stacked
    li.active
      a 有关联的
    - @related_models.each do |model|
      li
       = link_to model.title, ""
  / .module.border
    .header
      h5 有关联的
    .body
      - @related_models.each do |model|
        = link_to model.title, ""

app/views/partials/_search.html.slim
= form_tag "/#{controller_name}/search", :method => :get, :class => "form pull-left" do
  = search_field_tag "q", params[:q], :class => "search"

app/views/partials/_user_bar.html.slim
ul.nav.pull-right
  - if user_signed_in?
    li 
      = link_to "#", class: "js-menu" do
        ="#{current_user.name}  "
        b.caret.down
      ul.menu.rt
        li=link_to t("attributes.user.settings.title"), edit_user_registration_path
        li.divider
        li=link_to t("devise.base.sign_out"), sign_out_path
  - else
    li= link_to t("devise.base.sign_in"), sign_in_path
    li= link_to t("devise.base.sign_up"), sign_up_path